[project]
name = "dbs401-machielearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "deepagents>=0.0.5",
    "langchain[google-genai,openai]>=0.3.27",
    "pyodbc>=5.2.0",
    "python-dotenv>=1.1.1",
]
